apply plugin: 'com.android.application'

android {
    namespace 'com.example.toratele'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.toratele"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    // APKの名前を固定
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "ToraTele_Receiver.apk"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    
    // Media3 (ExoPlayer) の追加
    def media3_version = "1.1.1"
    implementation "androidx.media3:media3-exoplayer:$media3_version"
    implementation "androidx.media3:media3-ui:$media3_version"
    implementation "androidx.media3:media3-exoplayer-hls:$media3_version"
}
